# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'build/build.ps1'
    workingDirectory: 'build'
